# Generated by Django 5.2.1 on 2025-09-09 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('type', models.CharField(choices=[('payment_summary', 'Сводный отчет по платежам'), ('debt_report', 'Отчет по должникам'), ('plot_report', 'Отчет по участкам'), ('owner_report', 'Отчет по собственникам'), ('financial_report', 'Финансовый отчет'), ('custom_report', 'Пользовательский отчет')], max_length=50, verbose_name='Тип отчета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('query_params', models.JSONField(blank=True, default=dict, verbose_name='Параметры запроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Шаблон отчета',
                'verbose_name_plural': 'Шаблоны отчетов',
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10, verbose_name='Формат')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'В процессе'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Путь к файлу')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Размер файла (байт)')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Фильтры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сгенерировано')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Сгенерированный отчет',
                'verbose_name_plural': 'Сгенерированные отчеты',
                'ordering': ['-created_at'],
            },
        ),
    ]
