version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: sntacc_db
      POSTGRES_USER: sntacc_user
      POSTGRES_PASSWORD: sntacc_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_NAME=sntacc_db
      - DB_USER=sntacc_user
      - DB_PASSWORD=sntacc_pass
      - DB_HOST=db
      - DB_PORT=5432

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data: