# Generated by Django 5.2.1 on 2025-09-06 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(max_length=50, unique=True, verbose_name='Номер участка')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='Площадь (в сотках)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
                'ordering': ['plot_number'],
            },
        ),
        migrations.CreateModel(
            name='PlotOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_start', models.DateField(verbose_name='Дата начала владения')),
                ('ownership_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания владения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.owner', verbose_name='Собственник')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plots.plot', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Владелец участка',
                'verbose_name_plural': 'Владельцы участков',
                'ordering': ['-ownership_start'],
            },
        ),
    ]
