# Generated by Django 5.2.1 on 2025-09-09 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('date_paid', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('status', models.CharField(choices=[('paid', 'Оплачен'), ('not_paid', 'Не оплачен'), ('partial', 'Частично оплачен')], default='not_paid', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plots.plot', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-year', 'plot__plot_number'],
                'unique_together': {('plot', 'year')},
            },
        ),
    ]
