# Generated by Django 5.2.1 on 2025-09-09 17:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('view', 'Просмотр'), ('export', 'Экспорт'), ('import', 'Импорт'), ('send_notification', 'Отправка уведомления'), ('generate_report', 'Генерация отчета'), ('backup', 'Резервное копирование'), ('other', 'Другое')], max_length=50, verbose_name='Действие')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='Представление объекта')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Изменения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время')),
                ('additional_data', models.JSONField(blank=True, null=True, verbose_name='Дополнительные данные')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Записи аудита',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx'), models.Index(fields=['model_name', '-timestamp'], name='audit_audit_model_n_ad1f4e_idx')],
            },
        ),
    ]
