# Generated by Django 5.2.1 on 2025-09-09 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.IntegerField(default=0, verbose_name='Неудачные попытки входа'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя неудачная попытка'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lockout_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время блокировки'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя смена пароля'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='Двухфакторная аутентификация'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=100, verbose_name='Секретный ключ 2FA'),
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_password_length', models.IntegerField(default=8, verbose_name='Минимальная длина пароля')),
                ('require_uppercase', models.BooleanField(default=True, verbose_name='Требовать заглавные буквы')),
                ('require_lowercase', models.BooleanField(default=True, verbose_name='Требовать строчные буквы')),
                ('require_numbers', models.BooleanField(default=True, verbose_name='Требовать цифры')),
                ('require_special_chars', models.BooleanField(default=True, verbose_name='Требовать специальные символы')),
                ('password_expiry_days', models.IntegerField(default=90, verbose_name='Срок действия пароля (дней)')),
                ('max_failed_attempts', models.IntegerField(default=5, verbose_name='Максимум неудачных попыток')),
                ('lockout_duration', models.IntegerField(default=30, verbose_name='Длительность блокировки (минут)')),
                ('session_timeout', models.IntegerField(default=30, verbose_name='Таймаут сессии (минут)')),
                ('require_2fa_for_admins', models.BooleanField(default=True, verbose_name='Требовать 2FA для администраторов')),
                ('allow_2fa_for_users', models.BooleanField(default=True, verbose_name='Разрешить 2FA для пользователей')),
                ('log_login_attempts', models.BooleanField(default=True, verbose_name='Логировать попытки входа')),
                ('log_password_changes', models.BooleanField(default=True, verbose_name='Логировать смену паролей')),
                ('log_sensitive_actions', models.BooleanField(default=True, verbose_name='Логировать чувствительные действия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('snt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.snt', verbose_name='СНТ')),
            ],
            options={
                'verbose_name': 'Настройки безопасности',
                'verbose_name_plural': 'Настройки безопасности',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('success', models.BooleanField(verbose_name='Успешно')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('failure_reason', models.CharField(blank=True, max_length=100, verbose_name='Причина неудачи')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Попытка входа',
                'verbose_name_plural': 'Попытки входа',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', '-timestamp'], name='accounts_lo_ip_addr_eed231_idx'), models.Index(fields=['user', '-timestamp'], name='accounts_lo_user_id_6a9788_idx')],
            },
        ),
    ]
