# Generated by Django 5.2.1 on 2025-09-10 16:05

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
        ('plots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория документов',
                'verbose_name_plural': 'Категории документов',
            },
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тег документа',
                'verbose_name_plural': 'Теги документов',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('document_type', models.CharField(choices=[('receipt', 'Квитанция'), ('contract', 'Договор'), ('protocol', 'Протокол'), ('resolution', 'Решение'), ('invoice', 'Счет'), ('act', 'Акт'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to=documents.models.document_upload_path, verbose_name='Файл')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Размер файла (байт)')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='Тип файла')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активный'), ('archived', 'В архиве'), ('deleted', 'Удален')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загружено')),
                ('related_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='owners.owner', verbose_name='Связанный собственник')),
                ('related_plot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plots.plot', verbose_name='Связанный участок')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentcategory', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, to='documents.documenttag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', '-created_at'], name='documents_d_categor_66efd5_idx'), models.Index(fields=['document_type', '-created_at'], name='documents_d_documen_048969_idx'), models.Index(fields=['related_plot'], name='documents_d_related_25dd3b_idx'), models.Index(fields=['related_owner'], name='documents_d_related_a4cd66_idx')],
            },
        ),
    ]
