# Generated by Django 5.2.1 on 2025-09-09 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], max_length=20, verbose_name='Частота')),
                ('time', models.TimeField(verbose_name='Время запуска')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Расписание резервного копирования',
                'verbose_name_plural': 'Расписания резервного копирования',
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('type', models.CharField(choices=[('full', 'Полная копия'), ('incremental', 'Инкрементальная копия')], default='full', max_length=20, verbose_name='Тип')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'В процессе'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Путь к файлу')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Размер файла (байт)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Резервная копия',
                'verbose_name_plural': 'Резервные копии',
                'ordering': ['-created_at'],
            },
        ),
    ]
